### ISSUE TITLE
Cannot disable code syntax highlighting

### ISSUE THREAD

**Issue by wichtounet** [gu-fan/riv.vim#105]
Hi, 

I have a file with a lot of code and I suspect that syntax highlighting is making vim slow, but I cannot disable it. 

According to the docs, let g:riv_code_indicator = 0 should do the trick, but it does not do anything. I also tried to remove cpp from the list of the highlighted languages, but to no avail. 

How can I disable syntax highlighting for code blocks ? 

Thanks

**Comment by gu-fan** [comment]
https://github.com/gu-fan/riv.vim/blob/master/doc/riv_instruction.rst#g-riv-highlight-code 
Is this works?

**Comment by wichtounet** [comment]
@gu-fan Yes, this works perfectly! Thanks.
