### ISSUE TITLE
Variable name `pair` conflicts with other plugins

### ISSUE THREAD

**Issue by cjrh** [gu-fan/riv.vim#106]
Variable name `pair` on lines 24-25 in `after/syntax/rst.vim` here:

https://github.com/Rykka/riv.vim/blob/master/after/syntax/rst.vim#L24

seems to conflict with some other plugin.  I have many plugins installed, and haven't yet figured out which other plugin is defining pair.  However, when I change this variable name in the code above, e.g. to `delim_pair`, errors go away when opening RST files. 

This isn't a bug, but I just thought you should be aware of the issue, in case anyone else happens to report something similar.

**Comment by gu-fan** [comment]
... that's another plugin using a global name pair.. not me...
