### ISSUE TITLE
Riv Outline Third-level Indentation Doesn't Learn

### ISSUE THREAD

**Issue by wmhorne** [gu-fan/riv.vim#117]
My outline structure is:
    
    I. abcd
       a. akjdsahfahf
           i. dasflkjdaf

But Riv wants the third level to be an `I`, not an `i`. Can you change it so that it adapts to match the syntax of that level of the outline as used previously in the document?

**Comment by gu-fan** [comment]
Nope... it's level list symbol is hard coded..

https://github.com/gu-fan/riv.vim/blob/master/doc/riv_instruction.rst#lists
