### ISSUE TITLE
Textcolor in docstrings

### ISSUE THREAD

**Issue by DerWeh** [gu-fan/riv.vim#119]
Thank you for your awesome plug-in.
Would it be possible to (add an option to) keep the text color of the docstrings but have `rst` highlighting beside that? There is simply to little visual difference between docstrings and code, it makes it hard to differentiate that two at first glance.

**Comment by gu-fan** [comment]
don't understand... which docstring?

**Comment by DerWeh** [comment]
Sorry this was not very explicit. I am mostly using this plug-in to write doc-strings for my Python code. You offer the option `g:riv_python_rst_hl` to enable your plug-in for Python documents.

I would like to use it, but keep the normal text color like it is without the plug-in, to better distinguish it from the rest of my code. But of course I would like to have the rest of the advanced syntax highlighting your plug-in provides.

**Comment by gu-fan** [comment]
Understand, you mean the docstring keep the comment color of python

Got, I will change it.

And right now I'm changing the syntax highlighting in docstring and code highlighting, it's a bit buggy there.
