### ISSUE TITLE
`let g:riv_python_rst_hl=1` does not highlight section title correctly for indented python docstring

### ISSUE THREAD

**Issue by Jerry-Ma** [gu-fan/riv.vim#126]
Hi,

Thank you for this great plugin. It seems that after enabling highlighting python docstring, only the module level docstrings get fully rendered, while the indented docstrings (e.g., one for a method of a class) do not have their section titles rendered correctly due to the leading spaces. An simple example:

    #!/usr/bin/python
    """
    Module level doc string
    ------------------------
    The above section title gets highlighted correctly
    """
    class MyClass(object):
        def __init__(self):
            """
            Parameters
            ------------
            The above section title gets ignored by the rst renderer.
            However, other inline accents works as expected, like ``this one``
            """
            pass

**Comment by gu-fan** [comment]
.. maybe I should check that's python syntax  file, OK

**Comment by gu-fan** [comment]
mine here seems right,
![image](https://user-images.githubusercontent.com/579129/35151676-2e205016-fd5a-11e7-9297-f3bfb453e9ae.png)
