### ISSUE TITLE
test

### ISSUE THREAD

**Issue by gu-fan** [gu-fan/riv.vim#127]
![ezgif-4-ab9dadf953](https://user-images.githubusercontent.com/579129/34884998-79c29d5a-f7f9-11e7-9e86-a146ad1c54e0.gif)

**Comment by Rykka** [comment]
![ezgif-3-9bdcfb2d91](https://user-images.githubusercontent.com/579129/34885507-2f6cbd24-f7fb-11e7-93e4-6739f6afa1f9.gif)

**Comment by Rykka** [comment]
![ezgif-5-700c58247f](https://user-images.githubusercontent.com/579129/34886679-be522206-f7fe-11e7-8ba9-79c7b486a4cc.gif)

**Comment by Rykka** [comment]
![ezgif-5-93e6424202](https://user-images.githubusercontent.com/579129/34886822-58fa617e-f7ff-11e7-98a6-f287992ea749.gif)

**Comment by gu-fan** [comment]
![image](https://user-images.githubusercontent.com/579129/34906358-ecc497e2-f8a6-11e7-9e88-0625fed12531.png)

**Comment by gu-fan** [comment]
![image](https://user-images.githubusercontent.com/579129/34906362-108e5794-f8a7-11e7-897f-a80d5398323c.png)

**Comment by gu-fan** [comment]
![image](https://user-images.githubusercontent.com/579129/35139903-1485e406-fd30-11e7-965e-7c518d764423.png)

**Comment by gu-fan** [comment]
http://weixin.qq.com/r/HSo_Jl3EjgDxrRlF938P

**Comment by gu-fan** [comment]
https://weibo.com/pupupula

**Comment by gu-fan** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/579129/35188163-ea914ce8-fe6b-11e7-8a8e-11527785122b.gif)
