### ISSUE TITLE
Folding not working anymore 

### ISSUE THREAD

**Issue by Enrico68** [gu-fan/riv.vim#140]
After update I cant get folded sections anymore. I tried with the command `Riv-Reload` , but no success,

**Comment by tetrodoxin** [comment]
I second this one, no folding on a fresh install of vim. Always get the Message: No Fold found

Any Update  on that? What can I do to investigate/debug?

**Comment by jdw2003** [comment]
I had a play with this.  I now have to put the following line in my .vimrc

`let g:rst_fold_enabled=1`

**Comment by Enrico68** [comment]
For me it is fix, I close it
