### ISSUE TITLE
Let table support column span.

### ISSUE THREAD

**Issue by gu-fan** [gu-fan/riv.vim#17]
To support spaning column for table.

We should know and control the state of the border of each row.
when one row has changed, both the above and below border should be changed.

first find the changed column of the row, then other rows and borders  related column should be 
changed.

An action to span column could be added. maybe `:RivTableSpanColumn`

Row span will not be added currently.

**Comment by yuex** [comment]
What about using `+` as anchor, and then padding out the `|` and `-` between the anchors according to whether any `|` and `-` are found between. I doubt if it will be better to implement table auto-formatting via external programming language such as python. Of course, by this method there will be pits. But it should be able to cover some basic cases of row spanning and column spanning. I will try to find time to scrutinize the code. Any suggestion?

**Comment by databill** [comment]
This feature affects current writing again and again when I write rst documents more and more. The only thing I can do now is to avoid auto-correcting that is when editing avoids using ESC.

**Comment by gu-fan** [comment]
well, I don't use table that often....

I just write paragraphs...

**Comment by databill** [comment]
When I write a book or some research document, the table is the normal case.

Thanks for this great tool to help me.
I hope I can have some time to study your code and fix this issue. It's important to me.

**Comment by gu-fan** [comment]
well,
In fact, it's not easy mainly because of one thing.

the width and height of a cell is dynamic, 

u don't know wether this cell should be cross row/col, or just expand this cell and make a bigger table.
