### ISSUE TITLE
Rewrite the indent behavior

### ISSUE THREAD

**Issue by gu-fan** [gu-fan/riv.vim#71]
I want to rewrite the indent  behavior for riv.
1. list context:
   
   from row 1 to all (previously the 12/3/4 are all different).
   
   align to the start of last list item.
   with a `<Tab>` you can shift to the start of list content.
   further `<Tab>` will shift with `&sw` from the start of list content.
   with a `<S-tab>` shift to parent's edge or `&sw`
2. literal block and quote block :
   align to the start of item.
   shift with `&sw`
3. exp mark (comment/directive/etc.)
   align in `.. xxx`'s 'xxx' 
   shift with `&sw`
4. field list
   align in `:xxx: content`'s content
5. `<s-tab>` will always check parent's starting edge if it's over the current context.  e.g.:

```
     1. list 
         a. sub list 
             xxx xxxx::
             | align here.
            <s-tab> here will check sublist's edge, 
           then one more  <s-tab> will check list's edge. 

           for speed consideration, only list and list parent list are checked
```

That's all.

Any suggestions are welcome, But some time are needed to implement it.

also #63 and #68 mentioned this.

**Comment by kminh** [comment]
Hmm I'm using the latest version but behaviour 1 is still same as described in #63
