### ISSUE TITLE
RivHelpTodo is not working anymore and RivProjectlist not displaying correctly

### ISSUE THREAD

**Issue by Enrico68** [gu-fan/riv.vim#82]
I set two projects:

```
   let Works = { 'Name': 'My Working Notes', 'path': '~/Dropbox/rst',} 
   let Home = { 'Name': 'My Home Notes' , 'path': '~/Dropbox/rst2',}  
   let g:riv_projects = [Works, Home]  
```

With the command RivProjectList you get the list:

```
          1. My Note                 : ~/Dropbox/rst
          2. My Note                 : ~/Dropbox/rst2
          3. Temp Project         :  /var/folders/26/4_v2k57n5bd30n4zf9tdbxmm0000gn/
```

1) Why My Note names are displaying instead of Works and Home ?
2) The index directory points always to the 1st one (~/Dropbox/rst) even if you are working in the 2nd one
3) I have few todo lists in the two projects. The todo helper was displaying correctly but after the cache update sopped to work.

**Comment by gu-fan** [comment]
Oops , Got it

**Comment by gu-fan** [comment]
1. you should use 'name' instead of 'Name' 
2. I'll change it later
3. maybe remove cache in the future
