### ISSUE TITLE
Riv not working

### ISSUE THREAD

**Issue by Aradan** [gu-fan/riv.vim#83]
Hi, I downloaded the latest version but doing `RivQuickStart` does not produce anything. Also, when doing `RivTitle0` (and any title) I get the error

```
Input the title of level 0dateError detected while processing function riv#section#title:
line   51:
E121: Undefined variable: rows
E15: Invalid expression: rows == 3 ? 2-idx : rows-idx
line   53:
E121: Undefined variable: sft
E116: Invalid arguments for function append  
```

**Comment by Table10sHotShot** [comment]
Is there a fix for this?

**Comment by bcholfin** [comment]
I'm getting this too, with the current version.

**Comment by jgatkinsn** [comment]
When I do :RivQuickstart, I get E117: Unkown function: riv#action#tutor

**Comment by jgatkinsn** [comment]
reloading a new session (session man), and now :RivQuickStart & :RivInstruction does nothing

**Comment by albasili** [comment]
Is there a fix for this? I've the impression that when RivQuickStart is already launched then the second time it does not work, as if it cannot access some 'already opened' temporary file.

**Comment by ruppmatt** [comment]
I had this problem using vim installed via macports.

From what I've gathered, there is a problem with the python interpreter that was used to compile vim.  It may no longer be available.

My solution was simply to reinstall vim, set my python interpreter to the system one (27-apple) and install vim.  I then uninstalled my riv plugin and reinstalled it.

**Comment by albasili** [comment]
I'm not on mac and I'm not a big fan of uninstalling and reinstalling, but if there are no better ideas I will try it out.

**Comment by ob1c0d3Ordie** [comment]
Had the same problem. Just type the header title in your rst file and while your cursor is still on the same line switch to normal mode and type `":RivTitle0"` or any of the other title numbers available, or if you prefer key mappings use `<C-E>s0` etc.

**Comment by gu-fan** [comment]
Well,  sorry late
OS? vim？ Python version？

**Comment by gu-fan** [comment]
@thor You're absolutely right~
