### ISSUE TITLE
Make clickable.vim optional

### ISSUE THREAD

**Issue by GermainZ** [gu-fan/riv.vim#86]
I would prefer not to use clickable.vim. Could you please give us the option to disable the warning?

It should be enough to change this part in autoload/riv.vim:

```
if !exists("_t")
    echom "[RIV] clickable.vim is needed for link. Add it to your bundle"
endif
```

… to something like this:

```
if !exists("_t") && (!exists("g:riv_disable_clickable_warning") || g:riv_disable_clickable_warning == 0)
    echom "[RIV] clickable.vim is needed for link. Add it to your bundle"
endif
```

I was about to send a pull request, but wasn't sure if you want this or how you'd like to document it. Thanks.

**Comment by gu-fan** [comment]
this is disabled
