### ISSUE TITLE
Delete key is remapped as <Esc><tilde>

### ISSUE THREAD

**Issue by ostrokach** [gu-fan/riv.vim#89]
After installing `riv.vim` on neovim, my delete key started getting remapped to `<Esc>``<tilde>` whenever I am editing _.rdf_ files. It is similar to the following StackOverflow question: http://stackoverflow.com/questions/3230722/delete-key-is-changing-letter-case-in-vim, but in my case it is specific to `riv.vim`.

I have tried deleting the `./bundle` folder in `neovim` and reinstalling all the plugins, but the problem persists. I am using `Ubuntu 14.04` and `NVIM 0.0.0-alpha+201501211027`.

Also, I am not sure if it is related, but I first got the issue after using `InstantRst`. Now, whenever I open an `.rst` file, vim displays the following message:

```
"filename.rst" 3L, 30C
127.0.1.1
Press ENTER or type command to continue
```

**Comment by Rykka** [comment]
....

**Comment by fpytloun** [comment]
This solves the issue for me:
```let g:riv_ignored_imaps = "<Del>"```

**Comment by gu-fan** [comment]
merged , plz check
