### ISSUE TITLE
diary support? (feature request)

### ISSUE THREAD

**Issue by lotabout** [gu-fan/riv.vim#91]
Just like vimwiki that integrates with [calendar.vim](https://github.com/mattn/calendar-vim). 

More specifically:
1. open the calendar panel(calendar.vim)
2. select a date and hit <enter>.
3. open the diary file(year-month-day.rst) if exists else create a new one in the current riv project.

That  means riv's version of functions: `calendar_action` and `calendar_sign` should be implemented.

Is this going to be supported?

**Comment by gu-fan** [comment]
merged, plz check it
