### ISSUE TITLE
Syntax highliting not working for C code (but for C++)

### ISSUE THREAD

**Issue by HiPhish** [gu-fan/riv.vim#95]
Here is a snippet of C code:

```
.. code:: c

    while (iteration_counter < MAX_ITERATIONS && fabs(result) >= EPSILON)
```

This will not be highlighted by Riv. Changing the language from `c` to `cpp` gets syntax highlighting working. Since C is a subset of C++ at least syntax-wise they should be treated the same. A reader of the text file should know that a snippet of code is intended to be used in a C source file, so just replacing `c` with `cpp` in the user's document is not a good idea.

**Comment by HiPhish** [comment]
I did the following:

    :let g:riv_highlight_code .= ',c' 

but it's still not working for C code blocks.

**Comment by IngoHeimbach** [comment]
Getting the default value for `riv_highlight_code` from `riv.vim` and adding c as language in `.vimrc` does work for me:
```
let g:riv_highlight_code = "lua,python,c,cpp,javascript,vim,sh"
```

**Comment by HiPhish** [comment]
@IngoHeimbach No, doesn't work either. I have the following in my `ftplugin/riv.vim`
~~~~
let g:riv_highlight_code .= ',c'
~~~~
and echoing `echo g:riv_highlight_code` does give me `lua,python,cpp,javascript,vim,sh,c`, so it is in the list.

**Comment by IngoHeimbach** [comment]
Appending `,c` to `g:riv_highlight_code` doesn't work for me either. It seems that the order of languages is important for whatever reason. Please try so set `g:riv_highlight_code` directly with `c` before `cpp` as shown in my previous post.
