### ISSUE TITLE
fixdel does not exist in neovim

### ISSUE THREAD

**Issue by languitar** [gu-fan/riv.vim#96]
In neovim/neovim, the `fixdel` command does not exist anymore. This results in such warnings when opening a reStructured Text file:

```
E492: Not an editor command: fixdel
```

Would be nice if neovim/neovim was supported correctly and calling `fixdel` be made conditional.

**Comment by winged** [comment]
I've just stumbled upon this as well and fixed it - see PR #98 ;)

**Comment by HiPhish** [comment]
*bump* Why isn't the PR merged? It's a really simple and clean fix for the problem. I was about to do the same thing before I saw here that there is already a PR.

**Comment by gu-fan** [comment]
merged
